"""add super_admin role

Revision ID: 27ec703a04b5
Revises: 4eb02b2da039
Create Date: 2025-10-21 00:42:21.642728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ec703a04b5'
down_revision = '4eb02b2da039'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новое значение в enum userrole
    op.execute("ALTER TYPE userrole ADD VALUE 'super_admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


