services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: food_delivery_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Открываем порт для внешнего доступа
    networks:
      - food_delivery_network
    restart: unless-stopped

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: food_delivery_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Открываем порт для внешнего доступа
    networks:
      - food_delivery_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  food_delivery_network:
    driver: bridge
