name: Fresh Deploy to Production

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        
    - name: Fresh Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
          set -e
          echo "🚀 Starting fresh deployment..."
          
          # Очищаем старую директорию
          echo "🧹 Cleaning old deployment..."
          rm -rf ${{ secrets.SERVER_PATH }}
          mkdir -p ${{ secrets.SERVER_PATH }}
          
          # Клонируем репозиторий заново
          echo "📥 Cloning repository..."
          cd ${{ secrets.SERVER_PATH }}
          git clone https://PavelPanchenko:${{ secrets.GITHUB_TOKEN }}@github.com/PavelPanchenko/odostavka.online.git .
          
          # Создаем .env файл
          echo "⚙️ Creating .env file..."
          cp env.example .env
          
          # Останавливаем старые контейнеры
          echo "🛑 Stopping old services..."
          docker-compose down || true
          
          # Собираем образы
          echo "🔨 Building images..."
          docker-compose build --no-cache
          
          # Запускаем сервисы
          echo "🚀 Starting services..."
          docker-compose up -d
          
          # Очищаем неиспользуемые образы
          echo "🧹 Cleaning up..."
          docker system prune -f
          
          # Проверяем статус
          echo "📊 Checking service status..."
          docker-compose ps
          
          echo "✅ Fresh deployment completed successfully!"
        '
        
    - name: Health check
      run: |
        echo "🏥 Performing health checks..."
        sleep 30
        
        # Проверяем доступность API
        if curl -f -s https://api.${{ secrets.DOMAIN || 'odostavka.online' }}/health > /dev/null; then
          echo "✅ API health check passed"
        else
          echo "⚠️ API health check failed"
        fi
