name: Deploy to Production (RSYNC)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy via RSYNC
      run: |
        # Устанавливаем SSH ключ
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Добавляем сервер в known_hosts
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
        # Копируем файлы на сервер
        rsync -avz --delete \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='__pycache__' \
          --exclude='*.pyc' \
          --exclude='.env' \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/
        
        # Выполняем деплой на сервере
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd ${{ secrets.SERVER_PATH }}
          
          echo '🛑 Stopping services...'
          docker-compose down || true
          
          echo '🔨 Building images...'
          docker-compose build --no-cache
          
          echo '🚀 Starting services...'
          docker-compose up -d
          
          echo '📊 Checking service status...'
          docker-compose ps
        "
